name: Build For MacOS catalina
# Controls when the action will run. 
on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
jobs:
  macosbuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install deps
        run: |
          brew install automake
          brew install libpqxx 
          brew install pandoc 
          brew install bison 
          brew install flex
          brew install llvm

      - name: Build the app    
        run: |
          export CC=clang-10
          export CXX=clang++-10
          export CFLAGS="-O3 -g1 -fno-omit-frame-pointer"
          export CXXFLAGS="$CFLAGS -stdlib=libc++"
          ./autogen.sh
          ./configure  
          make -j2
